function A2=A2fun_Arri(vinf, aeavalue, aebvalue)

A2=[[0,                     0,      0, 0, 0, 0]; ...
    [0,                     0,  -vinf, 0, 0, 0]; ...
    [0,                  vinf,      0, 0, 0, 0]; ...
    [0,aeavalue*aebvalue*vinf,      0, 0, 0, 0]; ...
    [0,                     0,      0, 0, 0, 0]; ...
    [0,                     0,      0, 0, 0, 0]];
                        